### ISSUE TITLE
[Bug]: Buckets rendered upside down are not in the correct spot

### ISSUE THREAD

**Issue by benbenlaw** [cech12/CeramicBucket#66] opened 2023-01-09 12:06 UTC
### Minecraft Version

1.19.2

### Forge Version

43.2.0

### Mod Version

3.1.0.0

### Modpack or other Mod

seaopolis 2 

### Describe the Issue

buckets are incorrectly displayed if they are upside down
![image](https://user-images.githubusercontent.com/42780877/211304305-7cc5fb69-05c3-491d-a3bd-ecd298a42ae5.png)
![image](https://user-images.githubusercontent.com/42780877/211304345-2c5d354a-6ea1-483f-b1c0-3cf1701aaa33.png)

**Comment by cech12** [comment] 2023-01-09 12:26
Thanks for your report!

Does that only affect JEI?
Which mod adds the Steam?

**Comment by benbenlaw** [comment] 2023-01-09 12:28
in any inventory 
and mekanism adds steam

**Comment by benbenlaw** [comment] 2023-01-09 12:29
also energized glowstone from thermal does the same thing

**Comment by cech12** [comment] 2023-01-09 20:24
Thanks for your information! I will look into this :)

**Comment by cech12** [comment] 2023-01-09 22:19
The issue ist fixed in the upcoming BucketLib versions:
- 1.19-1.0.3.3 (1.19-1.19.2)
- 1.19.3-1.1.0.1 (1.19.3)

Thanks again for your report! When you find any other issue, please let me know. :)

**Closed as completed** 2023-01-09 22:20 UTC
Labels: bug
