### ISSUE TITLE
[HELP] Usage with FTB Quests

### ISSUE THREAD

**Issue by ItayKisous** [cech12/CeramicBucket#58] opened 2021-06-25 22:15 UTC
When trying to use ceramic buckets as an item quest I get stuck with a problem.
I don't know how to approach the tag section of the quest.
Tried doing "lava", "flowing_lava", "ceramic_cracking", "minecraft:lava", "ceramicbucket:ceramic_cracking" and nothing worked,
still any filled ceramic bucket would trigger the quest to complete.

Is there a way to make the only the bucket filled with lava trigger the quest to be complete?

**Comment by cech12** [comment] 2021-06-26 06:06
Thanks for informing me about this. I will look into that. :)

**Comment by cech12** [comment] 2021-06-26 15:32
That was a mess xD 

FTB Quests uses the Item Filters Mod as API to compare item stacks. This mod only compares the nbt values if the items are listed in the item tag `itemfilters:check_nbt`.

I added the items to this tag and the issue is fixed. It will be released in the next hours in the version 1.16.5-2.7.0

Thanks for your report! :)

**Closed as completed by cech12** 2021-06-26 15:32 UTC
Labels: enhancement, mod support
